//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.ApplicationDetail = new HashSet<ApplicationDetail>();
            this.AccountThirdPartyIdentity = new HashSet<AccountThirdPartyIdentity>();
            this.OfficialAccountApplication = new HashSet<OfficialAccountApplication>();
            this.OfficialAccountApplication1 = new HashSet<OfficialAccountApplication>();
            this.ChatRoomMember = new HashSet<ChatRoomMember>();
            this.Friend = new HashSet<Friend>();
            this.Friend1 = new HashSet<Friend>();
            this.OfficialMember = new HashSet<OfficialMember>();
            this.Post = new HashSet<Post>();
            this.PostComment = new HashSet<PostComment>();
            this.PostOperation = new HashSet<PostOperation>();
            this.StickerGroup = new HashSet<StickerGroup>();
        }
    
        public System.Guid AccountId { get; set; }
        public long AccountNo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.Guid> AvatarFileAgnetDataId { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTimeOffset> LockDateTime { get; set; }
        public string LockReason { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationDetail> ApplicationDetail { get; set; }
        public virtual FileAgentData FileAgentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountThirdPartyIdentity> AccountThirdPartyIdentity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficialAccountApplication> OfficialAccountApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficialAccountApplication> OfficialAccountApplication1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoomMember> ChatRoomMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friend> Friend1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficialMember> OfficialMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostOperation> PostOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StickerGroup> StickerGroup { get; set; }
    }
}
