//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountThirdPartyIdentity
    {
        public System.Guid AccountThirdPartyIdentityId { get; set; }
        public long AccountThirdPartyIdentityNo { get; set; }
        public System.Guid AccountId { get; set; }
        public int Provider { get; set; }
        public int Feild { get; set; }
        public string Value { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
