//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public System.Guid ApplicationDetailId { get; set; }
        public long ApplicationDetailNo { get; set; }
        public System.Guid OfficialAccountApplicationId { get; set; }
        public int Type { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
        public string Comment { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
        public Nullable<System.Guid> New_ReviewerAccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual OfficialAccountApplication OfficialAccountApplication { get; set; }
    }
}
