//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomRecord
    {
        public System.Guid ChatRoomRecordId { get; set; }
        public long ChatRoomRecordNo { get; set; }
        public System.Guid ChatRoomId { get; set; }
        public Nullable<System.Guid> ChatRoomMemberId { get; set; }
        public int Type { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> StickerId { get; set; }
        public Nullable<System.Guid> FileAgentDataId { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual ChatRoomMember ChatRoomMember { get; set; }
        public virtual Sticker Sticker { get; set; }
    }
}
