//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAgentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileAgentData()
        {
            this.Account = new HashSet<Account>();
            this.ChatRoom = new HashSet<ChatRoom>();
            this.Sticker = new HashSet<Sticker>();
        }
    
        public System.Guid FileAgentDataId { get; set; }
        public long FileAgentDataNo { get; set; }
        public int Type { get; set; }
        public string MimeType { get; set; }
        public string Filename { get; set; }
        public string Url { get; set; }
        public string ThumbnailUrl { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoom> ChatRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sticker> Sticker { get; set; }
    }
}
