//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SHLife_A07Entities : DbContext
    {
        public SHLife_A07Entities()
            : base("name=SHLife_A07Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<AccountThirdPartyIdentity> AccountThirdPartyIdentity { get; set; }
        public virtual DbSet<ApplicationDetail> ApplicationDetail { get; set; }
        public virtual DbSet<ChatRoom> ChatRoom { get; set; }
        public virtual DbSet<ChatRoomMember> ChatRoomMember { get; set; }
        public virtual DbSet<ChatRoomRecord> ChatRoomRecord { get; set; }
        public virtual DbSet<FileAgentData> FileAgentData { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<OfficialAccount> OfficialAccount { get; set; }
        public virtual DbSet<OfficialAccountApplication> OfficialAccountApplication { get; set; }
        public virtual DbSet<OfficialMember> OfficialMember { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostComment> PostComment { get; set; }
        public virtual DbSet<PostMedia> PostMedia { get; set; }
        public virtual DbSet<PostOperation> PostOperation { get; set; }
        public virtual DbSet<Sticker> Sticker { get; set; }
        public virtual DbSet<StickerGroup> StickerGroup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
