//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialAccountApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficialAccountApplication()
        {
            this.ApplicationDetail = new HashSet<ApplicationDetail>();
        }

        public System.Guid OfficialAccountApplicationId { get; set; }
        public long OfficialAccountApplicationNo { get; set; }
        public System.Guid OfficialAccountId { get; set; }
        public System.Guid AccountId { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> ReviewerAccountId { get; set; }
        public string Remark { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationDetail> ApplicationDetail { get; set; }
        public virtual OfficialAccount OfficialAccount { get; set; }
    }
}
