//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialMember
    {
        public System.Guid OfficialMemberId { get; set; }
        public long OfficialMemberNo { get; set; }
        public System.Guid OfficialAccountId { get; set; }
        public System.Guid AccountId { get; set; }
        public string MemberRole { get; set; }
        public int PermissionLevel { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> DeletionDateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual OfficialAccount OfficialAccount { get; set; }
    }
}
