//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfficialAccount()
        {
            this.OfficialAccountApplication = new HashSet<OfficialAccountApplication>();
            this.OfficialMember = new HashSet<OfficialMember>();
        }
    
        public System.Guid OfficialAccountId { get; set; }
        public long OfficialAccountNo { get; set; }
        public string OfficialName { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsVerified { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficialAccountApplication> OfficialAccountApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficialMember> OfficialMember { get; set; }
    }
}
