//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostComment()
        {
            this.PostComment1 = new HashSet<PostComment>();
        }
    
        public System.Guid PostCommentId { get; set; }
        public long PostCommentNo { get; set; }
        public System.Guid PostId { get; set; }
        public System.Guid AccountId { get; set; }
        public int Type { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> StickerId { get; set; }
        public Nullable<System.Guid> ReplyPostCommentId { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment1 { get; set; }
        public virtual PostComment PostComment2 { get; set; }
        public virtual Sticker Sticker { get; set; }
    }
}
