//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMedia
    {
        public System.Guid PostMediaId { get; set; }
        public long PostMediaNo { get; set; }
        public System.Guid PostId { get; set; }
        public int OrderNo { get; set; }
        public int Type { get; set; }
        public System.Guid FileAgentDataId { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
