//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife_SD1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sticker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sticker()
        {
            this.ChatRoomRecord = new HashSet<ChatRoomRecord>();
            this.PostComment = new HashSet<PostComment>();
        }
    
        public System.Guid StickerId { get; set; }
        public long StickerNo { get; set; }
        public System.Guid StickerGroupId { get; set; }
        public string Name { get; set; }
        public System.Guid FileAgentDataId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoomRecord> ChatRoomRecord { get; set; }
        public virtual FileAgentData FileAgentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostComment> PostComment { get; set; }
        public virtual StickerGroup StickerGroup { get; set; }
    }
}
